name: Release

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'finn-tbd-test-org/tbdex-js'
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
      id-token: write # necessary for NPM provenance

    name: Release
    runs-on: ubuntu-latest

    outputs:
      published: ${{ steps.changesets.outputs.published }}

    steps:
      - name: Checkout source
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          submodules: "true"

      # https://cashapp.github.io/hermit/usage/ci/
      - name: Init Hermit
        uses: cashapp/activate-hermit@v1

      - name: Install dependencies
        run: pnpm install

      - name: Build all workspace packages
        run: pnpm build

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        id: changesets
        with:
          publish: echo pnpm changeset publish
          version: echo pnpm changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish `next` preview
        if: steps.changesets.outputs.published != 'true' && steps.changesets.outputs.pullRequestNumber != '' && steps.changesets.outputs.hasChangesets == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout main
          SHORT_SHA=$(git rev-parse --short HEAD)
          pnpm changeset version --snapshot next-$SHORT_SHA
          pnpm changeset publish --no-git-tag --tag next

      - name: Generate SBOM files
        if: ${{ steps.changesets.outputs.published }}
        run: |
          # install fossa cli
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash

          # generate SBOM
          fossa report --format spdx attribution | tee tbdex-js.spdx
          fossa report --format cyclonedx-json attribution | tee tbdex-js.cydx.json
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        
      - name: Upload SBOMs as release artifacts
        uses: actions/upload-artifact@v3
        if: ${{ steps.changesets.outputs.published }}
        with:
          name: sbom@${{steps.changesets.outputs.publishedPackages[0].version}}
          path: |
            tbdex-js.spdx
            tbdex-js.cydx

  # publish-docs:
  #   needs: release
  #   name: Publish Docs
  #   if: ${{ needs.release.outputs.published == 'true' }}
  #   uses: ./.github/workflows/docs-publish.yml
