name: generate sboms (test)

on:
  push:
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SBOM files
        run: |
          # install fossa cli
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash

          # generate SBOM
          fossa report --format spdx attribution > tbdex-js.spdx
          fossa report --format cydx attribution > tbdex-js.cydx
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}

      - name: Upload SBOMs as release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: |
            tbdex-js.spdx
            tbdex-js.cydx